# Generated by Django 3.1.3 on 2020-11-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('mother_name', models.CharField(blank=True, max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('reg_no', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('stu_class', models.CharField(choices=[('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1'), ('inf', 'infant'), ('pre', 'prepatory')], max_length=3, verbose_name='class')),
                ('stu_sec', models.CharField(max_length=1, verbose_name='section')),
                ('stu_roll', models.IntegerField(verbose_name='Roll No.')),
                ('teaching_allowance', models.BooleanField(blank=True)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50)),
                ('post', models.CharField(blank=True, max_length=50)),
                ('pin', models.IntegerField()),
                ('dist', models.CharField(default='East Medinipur', max_length=50)),
                ('state', models.CharField(default='West Bengal', max_length=50)),
                ('primary_number', models.CharField(max_length=10)),
                ('whatsapp_number', models.CharField(blank=True, max_length=10)),
                ('mail', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.BooleanField(default=False)),
                ('january', models.BooleanField(default=False)),
                ('february', models.BooleanField(default=False)),
                ('march', models.BooleanField(default=False)),
                ('april', models.BooleanField(default=False)),
                ('may', models.BooleanField(default=False)),
                ('june', models.BooleanField(default=False)),
                ('july', models.BooleanField(default=False)),
                ('august', models.BooleanField(default=False)),
                ('september', models.BooleanField(default=False)),
                ('october', models.BooleanField(default=False)),
                ('november', models.BooleanField(default=False)),
                ('december', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
