# Generated by Django 3.1.3 on 2020-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='session_yr',
            field=models.CharField(default='2020-2021', max_length=10),
        ),
    ]
