# Generated by Django 3.1.3 on 2020-11-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20201119_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
