# Generated by Django 3.1.3 on 2020-11-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20201119_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
