# Generated by Django 3.1.3 on 2020-11-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='2020-2021', max_length=10)),
                ('stu_class', models.CharField(choices=[('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1'), ('inf', 'infant'), ('pre', 'prepatory')], max_length=3)),
                ('tuition_fee', models.IntegerField(default=0)),
                ('tiffin_Charges', models.IntegerField(default=0)),
                ('conveyance_charges', models.IntegerField(default=0)),
                ('computer_charges', models.IntegerField(default=0)),
                ('others', models.IntegerField(default=0)),
                ('session_charge', models.IntegerField(default=0)),
                ('admission_fee', models.IntegerField(default=0)),
                ('examination_fees', models.IntegerField(default=0)),
                ('library_fee', models.IntegerField(default=0)),
                ('saraswati_puja', models.IntegerField(default=0)),
                ('cultural_fee', models.IntegerField(default=0)),
                ('game_fee', models.IntegerField(default=0)),
                ('electric_fee', models.IntegerField(default=0)),
                ('badge', models.IntegerField(default=0)),
                ('medical', models.IntegerField(default=0)),
                ('ifrastructure_fee', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('trxn_no', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
