# Generated by Django 3.1.3 on 2020-11-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
