# Generated by Django 3.1.3 on 2020-11-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='billed_amount',
            field=models.IntegerField(default=0, verbose_name='billed amount'),
            preserve_default=False,
        ),
    ]
