# Generated by Django 3.1.3 on 2020-11-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201119_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='collected_amount',
            field=models.IntegerField(default=0, verbose_name='amount collected'),
            preserve_default=False,
        ),
    ]
