# Generated by Django 3.1.3 on 2020-11-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_collected_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode',
            field=models.CharField(default='offline', max_length=20),
        ),
    ]
