# Generated by Django 3.1.3 on 2020-11-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20201120_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='details',
        ),
    ]
