# Generated by Django 3.1.3 on 2020-11-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_transaction_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='details',
        ),
    ]
